server:
  port: 9999
  servlet:
    context-path: /corgi-meta
spring:
  application:
    name: corgi-meta
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/corgi_meta?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: egova
  liquibase:
    change-log: db/changelog/database-changelog.yaml
  security:
    user:
      name: admin
      password: admin
logging:
  file:
    path: logs/${spring.application.name}
  level:
    root: info
springdoc:
  swagger-ui:
    path: /swagger-ui.html
knife4j:
  enable: true
  setting:
    language: zh_cn